name: gh-pages

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  gen_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: .docs

      - name: Generate docs
        run: |
          make docs

      - name: Push
        run: |
          cd ${GITHUB_WORKSPACE}/.docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
